---
title: "exploring lexique"
author: "Christophe Pallier <christophe@pallier.org>"
date: "03/02/2015"
output: html_document
---

We load lexique:

```{r load}
a = read.csv('lexique_small.csv', fileEncoding='utf-8')
a = subset(a, gramcat=='NOM')
```

First we plot the histogram of log10 of the frequencies of word


```{r histo}
data = hist(log10(a$freq), nclass=100)
plot(data$breaks[-1], log10(data$counts))
```

Now, we select words 

```{r}
lf4 = a$word[a$nbletters==4 & (log10(a$freq)>0.5) & log10(a$freq)<1]
hf4 = a$word[a$nbletters==4 & (log10(a$freq)>2) & log10(a$freq)<3]
lf6 = a$word[a$nbletters==6 & (log10(a$freq)>0.5) & log10(a$freq)<1]
hf6 = a$word[a$nbletters==6 & (log10(a$freq)>2) & log10(a$freq)<3]
```


```{r}
nitems = 45
lf4final = as.character(sample(lf4, nitems))
hf4final = as.character(sample(hf4, nitems))
lf6final = as.character(sample(lf6, nitems))
hf6final = as.character(sample(hf6, nitems))

```

```{r}
d = data.frame(length=gl(2, 90, 180, labels=c('l4','l6')),
               freq=gl(2, 45, 180, labels=c('lf', 'hf')),
               item=c(lf4final, hf4final, lf6final, hf6final))
write.csv(d, "words.csv")
```

